--- # YoloV5 training parameters
weights: yolov5s.pt
cfg: ''
data: 'data/coco128.yaml'
hyp: 'data/hyps/hyp.scratch.yaml'
epochs: 10
batch_size: 16
img_size: 512
rect : False
resume: False
nosave: False
noval: False
noautoanchor: False
evolve : False
bucket: ''
cache: False
image_weights: False
device: ''
multi_scale: False
single_cls: False
adam: False
sync_bn: False
workers: 8
project: 'runs'
name: 'exp'
exist_ok: False
quad: False
linear_lr: False
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: 1
local_rank: -1
